### PR TITLE
Add collector.yaml config per upstream documentation

### PR DESCRIPTION
**Pull request by jasonschulte**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-scrutiny/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add collector.yaml config per upstream documentation

## Benefits of this PR and context:

Initialize collector.yaml configuration file to /config volume and allow it to be customized

## How Has This Been Tested?

This was tested by building and deploying the container on my local machine

### CODE REVIEW

**Comment by PixelJonas** [comment]
👍  Just came here because I was missing this config option. I hope this gets merged soon

**Comment by PixelJonas** [comment]
this is still relevant. I use that PR in my fork and it's working great

**Comment by PixelJonas** [comment]
keeping this alive :D I run this change Dec 2020 without any problems

**Comment by alex-phillips** [comment]
Looks good, thanks!

**Pull request merged**
